name: Inputs and Outputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: "Skip deployment and only print build output"
      target:
        type: environment
        required: true
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: "Release from which to build and deploy"
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "Choose the build status for the demo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "GITHUB_OUTPUT path: $GITHUB_OUTPUT"

      - name: Build
        id: build
        run: |
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          echo "status=${{ github.event.inputs['build-status'] }}" >> $GITHUB_OUTPUT
    outputs:
          build-status: ${{ steps.build.outputs.status }}
          tag: ${{ github.event.inputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: >
      needs.build.result == 'success' &&
      ${{ inputs.dry-run }} == false &&
      needs.build.outputs['build-status'] == 'success'
    environment: ${{ github.event.inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to '${{ github.event.inputs.target }}' using tag '${{needs.build.outputs.tag }}'"
